### ISSUE TITLE
Consistent function def

### ISSUE THREAD

**Issue by bliof** [KaloyanKaludov/Element#1]
I think that this looks better:

```
sum (a, b) :: a + b
sum :: $ + $1

(a, b) :: a + b
:: $ + $1
```

Or something other that keeps the both type of functions look-a-like

At the moment you do:

```
sum:(a) a + $
sum :: $ + $1
```

ps. I've looked only at https://github.com/KaloyanKaludov/Element/blob/18e5e1d1197447037113a2f4825c88b1713257cc/examples/functions.element

**Comment by KaloyanKaludov** [comment]
Hi!

That was the original idea actually, however it is more difficult to parse
because it requires a lot of look-ahead.
In the case when you have something like:

f = (a) :: a + 1
f = (a  + b) \* c

When the parser reads the "(" it will not be able to immediately determine
if this is supposed to be a function definition or an arithmetic expression.
I actually do more then one character look-ahead in the case when I have to
check if there is an "else" clause after an "if" expression, but I consider
it a kind of hack.
Ideally the language grammar should be LL(1) (
https://en.wikipedia.org/wiki/LL_parser).

For similar reasons there is need for a separate syntax when you don't
explicitly specify any arguments. Originally the idea was something like:

f = :(a) a + 1
f = : $ + 1

However this creates the same problem when the function body starts with an
arithmetic expression as in:

f = : (a + b) \* c

And this is how I came to the current syntax rule.

Regards,
Kaloyan

On Thu, May 19, 2016 at 3:40 PM, Aleksandar Ivanov <notifications@github.com

**Comment by bliof** [comment]
```
f = (a) :: a + 1
f = (a  + b) * c
```

Is it backtracking if you "peek" whether there is `::` after the closing bracket?
That is:

```
f = (a) :: a + 1
    ^ - I have something in brackets
f = (a) :: a + 1
      ^ - It ended
f = x :: a + 1
    ^ x = (a)

f = x :: a + 1
      ^ - I have a lambda, so.. pass the x if it is present to the lambda builder. This builder should croak if there is a problem with brackets expression
```

The second `f = (a  + b) * c` is parsed like now, with no additional constraints on the data added by `::`. Well you should be able to execute it but ¯_(ツ)_/¯

ps. Just a thought - there could be a tuple type that you pass to the lambda block.
ps 2. The same goes for the if-else, no look-ahead needed.

**Comment by KaloyanKaludov** [comment]
Yes, this kind of peeking/backtracking/more-than-one-token-lookahead is
exactly what I am trying to avoid.
It violates the idea of a LL(1) parser which most modern programming
languages follow.

Making it work like this would introduce multiple places where the parser
will have to "peek" an arbitrary amount of tokens ahead to determine what
it is currently trying to parse.
It would complicate any place in the parser where a "(" is encountered
(function definitions, function calls, arithmetic), because it would have
to read all the way to after the ")" to figure out the current expression.

Right now the rule of thumb is quite simple actually even purely for
readability purposes:
"If it starts with ":" or "::" then it is a function definition"

As far as tuples are concerned, I was thinking of adding them as a kind of
an internal structure to help with multiple assignment and multiple return
values. But this is only for internal representation inside the VM. In
actual code their function pretty much overlaps with the idea of a "fixed
size array", so I consider them kind of redundant.

About using tuples as argument lists to function calls. The parser
currently uses an "ArgumentsNode" structure which I guess is what you mean.
This indeed simplifies some of the code since the "(" token is treated as a
binary operator between the function name (lambda definition) and the
arguments list. This way the function calls are in the same precedence
table as the rest of the operators.
